export const AcousticGrandPiano = {
	A0: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A0.mp3',
	Bb0: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb0.mp3',
	B0: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B0.mp3',

	C1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C1.mp3',
	Db1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db1.mp3',
	D1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D1.mp3',
	Eb1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb1.mp3',
	E1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E1.mp3',
	F1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F1.mp3',
	Gb1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb1.mp3',
	G1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G1.mp3',
	Ab1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab1.mp3',
	A1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A1.mp3',
	Bb1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb1.mp3',
	B1: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B1.mp3',

	C2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C2.mp3',
	Db2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db2.mp3',
	D2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D2.mp3',
	Eb2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb2.mp3',
	E2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E2.mp3',
	F2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F2.mp3',
	Gb2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb2.mp3',
	G2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G2.mp3',
	Ab2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab2.mp3',
	A2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A2.mp3',
	Bb2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb2.mp3',
	B2: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B2.mp3',

	C3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C3.mp3',
	Db3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db3.mp3',
	D3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D3.mp3',
	Eb3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb3.mp3',
	E3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E3.mp3',
	F3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F3.mp3',
	Gb3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb3.mp3',
	G3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G3.mp3',
	Ab3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab3.mp3',
	A3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A3.mp3',
	Bb3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb3.mp3',
	B3: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B3.mp3',

	C4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C4.mp3',
	Db4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db4.mp3',
	D4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D4.mp3',
	Eb4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb4.mp3',
	E4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E4.mp3',
	F4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F4.mp3',
	Gb4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb4.mp3',
	G4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G4.mp3',
	Ab4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab4.mp3',
	A4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A4.mp3',
	Bb4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb4.mp3',
	B4: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B4.mp3',

	C5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C5.mp3',
	Db5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db5.mp3',
	D5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D5.mp3',
	Eb5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb5.mp3',
	E5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E5.mp3',
	F5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F5.mp3',
	Gb5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb5.mp3',
	G5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G5.mp3',
	Ab5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab5.mp3',
	A5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A5.mp3',
	Bb5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb5.mp3',
	B5: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B5.mp3',

	C6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C6.mp3',
	Db6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db6.mp3',
	D6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D6.mp3',
	Eb6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb6.mp3',
	E6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E6.mp3',
	F6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F6.mp3',
	Gb6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb6.mp3',
	G6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G6.mp3',
	Ab6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab6.mp3',
	A6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A6.mp3',
	Bb6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb6.mp3',
	B6: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B6.mp3',

	C7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/C7.mp3',
	Db7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Db7.mp3',
	D7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/D7.mp3',
	Eb7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Eb7.mp3',
	E7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/E7.mp3',
	F7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/F7.mp3',
	Gb7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Gb7.mp3',
	G7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/G7.mp3',
	Ab7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Ab7.mp3',
	A7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/A7.mp3',
	Bb7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/Bb7.mp3',
	B7: 'http://localhost:3001/soundfonts/acoustic_grand_piano/B7.mp3'
};
